-- Shared ledger marker: applied from ../trackr/ to the hosted database on 2026-10-04.
-- Finance-owned SQL is maintained in ../trackr/supabase/migrations/20261004165900_finance_main_alignment.sql
-- This marker prevents replaying finance changes from the fitness repository.
