-- Shared ledger marker: applied from ../trackr/ to the hosted database on 2026-10-04.
-- Finance-owned SQL is maintained in ../trackr/supabase/migrations/20261004170400_atomic_order_updates.sql
-- This marker prevents replaying finance changes from the fitness repository.
